# This file was generated by GoReleaser. DO NOT EDIT.
cask "elgato" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "900bf2a8cafbb361906ccdeaef778b9fbd130e83eb25e4c7ad2c0378ed8efcae"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "58ffc1a0ffa94bac60d5e8d1d8fef1b4c0040c6072a28f0ce1a1d674ba573736"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "672bd6ce3cda007ff7334d91cdd111a87201fd921791483ec14a498587b6f381"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67bb93643e57a4896fd39d25b3490268af4930959444470146021cd0e8af746a"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_linux_arm64.tar.gz"
    end
  end

  name "elgato"
  desc "Control Elgato Key Lights from the command line"
  homepage "https://github.com/arventures/elgato"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elgato"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/elgato"]
    end
  end

  # No zap stanza required

end
