# This file was generated by GoReleaser. DO NOT EDIT.
cask "elgato" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e476d87661715d14bf80caeaeee0be47f994a63c4417dc39486df947f47b38c9"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5475646e4efb4f1c31874376c538f64064bbd385f97232dfee374704069bcea9"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "680f9c42823b0f525fa50b30ec382188c0768ba5faf8f468c4ce478a18aa5701"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ef1cca41a258d9c7bc00eb0a5cf14275618f569f92a127d06bf41084b4ecaba"
      url "https://github.com/arventures/elgato/releases/download/v#{version}/elgato_linux_arm64.tar.gz"
    end
  end

  name "elgato"
  desc "Control Elgato Key Lights from the command line"
  homepage "https://github.com/arventures/elgato"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elgato"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/elgato"]
    end
  end

  # No zap stanza required

end
